name: DevSecOps Security

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:

  sca:
    name: SCA - Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run SCA
        uses: aquasecurity/trivy-action@0.36.0
        with:
          scan-type: fs
          scan-ref: ./app
          scanners: vuln
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

  container:
    name: Container Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build \
            -t devsecops-lab:${{ github.sha }} \
            .
      - name: Scan Container
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: devsecops-lab:${{ github.sha }}
          format: table
          scanners: vuln
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
